# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litclock < Formula
  desc ""
  homepage "https://github.com/borischen0203/homebrew-litclock"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.7/litclock_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "311fb2ab55391e0cba96577ba3867949dac767aec60a6c6acc53ad55d6208820"

      def install
        bin.install "litclock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.7/litclock_0.0.7_Darwin_arm64.tar.gz"
      sha256 "4936802ae9fbee66f527825c550ed41ce9e913073934a4614df53d533dbff0da"

      def install
        bin.install "litclock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.7/litclock_0.0.7_Linux_x86_64.tar.gz"
      sha256 "56ec13c313e1b9c0e358191ba544e7840963b8b5b43d4eb82015b072e9169667"

      def install
        bin.install "litclock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.7/litclock_0.0.7_Linux_arm64.tar.gz"
      sha256 "52c3b027300a691dbae435e74bf8e10db5c1498af50755b5597830540d235862"

      def install
        bin.install "litclock"
      end
    end
  end
end
