# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litclock < Formula
  desc ""
  homepage "https://github.com/borischen0203/homebrew-litclock"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.5/litclock_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "c00680365783316fcb772b6531bbf9d3127fb25ff92fceedcde57f6a9453dcc1"

      def install
        bin.install "litclock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.5/litclock_0.0.5_Darwin_arm64.tar.gz"
      sha256 "0b70e1dd60e1f363787692f099cdbb5ae645e02a234dd15010cf17d246c681f9"

      def install
        bin.install "litclock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.5/litclock_0.0.5_Linux_arm64.tar.gz"
      sha256 "651fb73b7785999522b12f5b57d0dc124a88860d45b8ea9b6a8e194dd1e9dcc8"

      def install
        bin.install "litclock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/litclock/releases/download/v0.0.5/litclock_0.0.5_Linux_x86_64.tar.gz"
      sha256 "dcb66b399088b4fa4e451241d4971edadd12dc8872886a5b6f34c9db9020d737"

      def install
        bin.install "litclock"
      end
    end
  end
end
